# lefthook.yml

# Build commit messages
prepare-commit-msg:
  commands:
    commitzen:
      interactive: true
      run: >
        if [ "$LEFTHOOK" = "0" ] || [ -n "$AMEND" ]; then
          exit 0;
        fi;
        if [ "$2" = "message" ] || [ "$2" = "template" ] || [ "$2" = "merge" ] || [ "$2" = "squash" ]; then
          exit 0;
        fi;
        exec < /dev/tty && npx cz --hook || true

# Format files
pre-commit:
  commands:
    prettier:
      glob: '*.{js,jsx,ts,tsx,json,css,scss,md}'
      run: npx prettier --write {staged_files}

# Validate commit messages
commit-msg:
  commands:
    'lint commit message':
      run: npx commitlint --edit {1}
