packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: ^19.0.0
  '@types/react': ^19.0.0
  react-dom: ^19.0.0
  '@types/react-dom': ^19.0.0
  tailwindcss: ^4.0.0
  typescript: ^5.0.0
  eslint: ^9.0.0
  '@types/node': ^20.0.0
